apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-audit
  namespace: demo
  labels:
    app: git-audit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-audit
  template:
    metadata:
      labels:
        app: git-audit
    spec:
      containers:
        - name: git-audit
          image: josefpodanyml/git-audit:latest
          args: ["server", "--port", "8080"]
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
